### ISSUE TITLE
Filename is not identified correctly

### ISSUE THREAD

**Issue by errotu** [danijoo/sync_zotero_remarkable#3]
I've set up a WebDav-configuration by now. Unfortunately, a new error occurs:

#### Processing files ####

Full Text PDF download, unzip,Traceback (most recent call last):
  File ".local/bin/sync_zotero_rm", line 101, in <module>
    zip.extract(title, path=tempdir.name)
  File "/usr/lib/python3.8/zipfile.py", line 1630, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python3.8/zipfile.py", line 1669, in _extract_member
    member = self.getinfo(member)
  File "/usr/lib/python3.8/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'Full Text PDF' in the archive"

It seems like the script is looking for a file with the name of the title it has in Zotero, not with the actual filename (which is in this case: [Author] - [Year] - [Title].pdf)

**Comment by dnlbauer** [comment]
Interesting. for my setup `title` and `filename` returns the same value. Thanks for the PR, I will merge it :+1:
